name: CI

on: [push]

jobs:
    build:
        name: Lint and run tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/setup-node@v1

            - name: Run CI
              run: |
                  cd frontend/
                  npm install
                  npm run lint
