version: "3.7"
services:
    mongo:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - strapi-app-network
        volumes:
            - strapidata:/data/db
        ports:
            - "27017:27017"

    backend:
        image: strapi/strapi
        container_name: backend
        restart: unless-stopped
        env_file: .env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        networks:
            - strapi-app-network
            - graphql-network
        depends_on:
            - mongo
        volumes:
            - ./backend:/srv/app
        ports:
            - "1337:1337"

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        container_name: frontend
        stdin_open: true
        networks:
            - graphql-network
        volumes:
            - ./frontend:/srv/frontend
            - /srv/frontend/node_modules

volumes:
    strapidata:

networks:
    strapi-app-network:
        driver: bridge
    graphql-network:
        driver: bridge
